steps:
# If using subfolder from repo root to build, you need to specify the relative location for each stage
# Kaniko: dockerfile location and context dir
# General build step: dir: arg for step
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=Dockerfile
  - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/kayak-frontend/kayak-frontend
  - --cache=true
  - --cache-ttl=6h
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'kayak-frontend', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/kayak-frontend/kayak-frontend', '--region', 'us-central1', '--allow-unauthenticated']