[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-cloud-pubsub",
    "pyfirmata2",
    "Phidget22",
    "pyyaml",
    "python-dotenv",
]
